version: '3.8'

services:
  mygame:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
      - ./music:/app/music
    ports:
      - "5000:5000"
    environment:
      - PYTHONUNBUFFERED=1
    command: python src/main.py

networks:
  default:
    driver: bridge